### ISSUE TITLE
Missing standard MBean in JMinix

### ISSUE THREAD

**Issue by jimmysyss** [lbovet/jminix#13]
I am working in a Spring application with Logback, I would like to use JMinix to enable the online configuration of logging level. However, I can only see MBean as followed, but not the Logback one

![image](https://cloud.githubusercontent.com/assets/1673493/25512293/2ba9fd5a-2bff-11e7-8537-b1d84b938356.png)

> <bean id="mbeanServer" class="org.springframework.jmx.support.MBeanServerFactoryBean"/>

    <bean id="exporter" class="org.springframework.jmx.export.MBeanExporter">
        <property name="autodetect" value="true"/>
        <property name="server" ref="mbeanServer"/>
    </bean>

**Comment by jimmysyss** [comment]
I figure out the reason myself, I should rely on Default mbeanServer lookup, rather than specifying Spring mbeanServer. 

Thanks

**Comment by lbovet** [comment]
Closing since answered by author
