### ISSUE TITLE
jminix errors out when deploying on tomcat 9

### ISSUE THREAD

**Issue by radai-rosenblatt** [lbovet/jminix#15]
i've followed the instructions in adding a jminix servlet to my web.xml

when loading the jminix page i get an empty browser (all the static files are loaded, but nothing displayed in the tree borwser) and the following javascript error in my firefox console:

```
Error: dijit.tree.TreeStoreModel: query "" returned undefined items, but must return exactly one item Stack trace: getRoot/<.onComplete<@js/dojotoolkit/dojo/../dijit/tree/TreeStoreModel.js:29:7 dojo.hitch/<@http://localhost:8080/impl-war-1.0-SNAPSHOT/jmx/js/dojotoolkit/dojo/dojo.js:16:15296 fetch/<@js/dojotoolkit/dojo/../dojox/data/ServiceStore.js:113:1
```

the very last request  i see made is to /servers, which returns "0". i can manually browse to /servers/0/ and see contents, so this appears to be a client-side issue?

**Comment by oxc** [comment]
I believe the issue is that the response has a `text/plain` content type, not `application/json`. 

For me this happens when running Tomcat 8.5 on Java 11, with 8.5 on Java 8 it works.

**Comment by ipalopezhentsev** [comment]
To @oxc : Thanks for the observation! have you managed to solve it using jdk11? I've digged into it and it seems that JDK 8 returns StringRepresentation whereas JDK 11 returns TemplateRepresentation. I've tried changing it, along with content type, but it hasn't helped...

As it is, jminix seems to be incompatible with JDK 11...

**Comment by oxc** [comment]
It works a bit better if I force the restlet dependencies to version 2.4.1, but then it breaks elsewhere. 
I've decided to switch to another implementation.

**Comment by ipalopezhentsev** [comment]
@oxc : Thanks! out of interest, what other implementation did you choose?

**Comment by oxc** [comment]
@ipalopezhentsev  Nothing has been finally decided yet, but I've looked into [hawt.io](https://hawt.io/) (and probably standalone [jolokia](https://jolokia.org) agents for script access).

**Comment by ipalopezhentsev** [comment]
@oxc we've just managed to get it working by upgrading to restlet 2.4.0 (i.e. you exclude bundled restlet from jminix via pom and replace it with the new version)

**Comment by oxc** [comment]
@ipalopezhentsev, and you can call all exported methods? This didn't work for me, even with restlet 2.4.x

**Comment by ipalopezhentsev** [comment]
@oxc yes, everything seems to work.

**Comment by oxc** [comment]
For the record: I cannot confirm that, executing operations still does not work (at least it does not display the return value).

**Comment by ipalopezhentsev** [comment]
@oxc are you sure that return value is not an empty string? recent versions of jminix have that bug. I.e. operation is executed, but web ui doesn't reflect that in any way

**Comment by tzdunek** [comment]
Hello Guys
**Is this thread about tomcat 9 only, or about JAVA 11 too?**
I upgraded tomcat to 9 (on JAVA 8 ) and it worked fine with default restlet version 2.1.4 and jminix 1.2.0.

But with JAVA 11 it was empty jminix page table.
I had also such 2 warnings during aspectj compilation:
```
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ <project name>
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1244 source files ...
...
[INFO] --- aspectj-maven-plugin:1.11.1:compile (default) @ <project name>
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[WARNING] invalid Class-Path header in manifest of jar file: <home_path>\.m2\repository\org\restlet\jee\org.restlet\2.1.4\org.restlet-2.1.4.jar
invalid Class-Path header in manifest of jar file: <home_path>\.m2\repository\org\restlet\jee\org.restlet.ext.servlet\2.1.4\org.restlet.ext.servlet-2.1.4.jar
```
**When I switched to restlet 2.4.0 (as you advised above), jminix GUI works fine.**
But still I see one WARNING during maven compilation:

```
[INFO] --- aspectj-maven-plugin:1.11.1:compile (default) @ <project name>
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[WARNING] invalid Class-Path header in manifest of jar file: <home_path>\.m2\repository\org\restlet\jee\org.restlet.ext.servlet\2.4.0\org.restlet.ext.servlet-2.4.0.jar
```

**Tomcat startup log:**
```
INFO: dispatcherJMiniX: [Restlet] ServerServlet: component class is null
```

**What do you think about this WARNING and strange INFO?**

> ```
> [WARNING] invalid Class-Path header in manifest of jar file: <home_path>\.m2\repository\org\restlet\jee\org.restlet.ext.servlet\2.4.0\org.restlet.ext.servlet-2.4.0.jar
> ```
> ```
> INFO: dispatcherJMiniX: [Restlet] ServerServlet: component class is null
> ```
