### ISSUE TITLE
AttributeFilter not applied to array elements

### ISSUE THREAD

**Issue by pulquero** [lbovet/jminix#20]
Array elements are just converted to a string here:
https://github.com/lbovet/jminix/blob/254c172df2ecccb321779bdcca70bf49019596f8/src/main/java/org/jminix/console/resource/AttributeResource.java#L90
This should be a fallback, and first data[i] should be passed through AttributeFilter. At the very least, if AttributeFilter returns HtmlContent then this should be rendered instead.

**Comment by lbovet** [comment]
Do you have the possibility to submit a Pull Request? I lack capacity to implement and test.

**Comment by pulquero** [comment]
Yes, I can do that.

**Comment by lbovet** [comment]
Fixed by #22
