### ISSUE TITLE
ContentFilter for Operations

### ISSUE THREAD

**Issue by mtrovo** [lbovet/jminix#6]
I have an application which relies heavily on JMX operations for ops reports and I'm needing the same kind of functionality that attributeFilter provides but for the operation return value.

For example I have several operations which queries with certain parameters and return a HTML string as a value, I would like to see this content served as HTML, not as plain text.

**Comment by lbovet** [comment]
This is already available, at least on the master branch head. 
Your MBean operation just has to return a HtmlContent object, as for attributes.
The next jminix release will surely include it.
